project:
  type: website
  output-dir: docs

website:
  title: "SDS List"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-expand: true

editor: source

