---
title: "Lab E1.12 - Teaching Laboratory I"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(icon)
library(kableExtra)
library(formattable)
library(dplyr)
```

```{r include=FALSE}

# loading the main table from csv
lista_reagenti <- read.csv2("lista_sds.csv", header = TRUE)

#colnames(lista_consumabili) <- c("Reagent", "Code", "Company", "Weight", "Quantity", "Note",...)

# subsetting the main table
letter_A <- subset(lista_reagenti, filter_name == "A")

letter_B <- subset(lista_reagenti, filter_name == "B")

letter_C <- subset(lista_reagenti, filter_name == "C")

letter_D <- subset(lista_reagenti, filter_name == "D")

letter_E <- subset(lista_reagenti, filter_name == "E")

letter_F <- subset(lista_reagenti, filter_name == "F")

letter_G <- subset(lista_reagenti, filter_name == "G")

letter_H <- subset(lista_reagenti, filter_name == "H")

letter_I <- subset(lista_reagenti, filter_name == "I")

letter_J <- subset(lista_reagenti, filter_name == "J")

letter_K <- subset(lista_reagenti, filter_name == "K")

letter_L <- subset(lista_reagenti, filter_name == "L")

letter_M <- subset(lista_reagenti, filter_name == "M")

letter_N <- subset(lista_reagenti, filter_name == "N")

letter_O <- subset(lista_reagenti, filter_name == "O")

letter_P <- subset(lista_reagenti, filter_name == "P")

letter_Q <- subset(lista_reagenti, filter_name == "Q")

letter_R <- subset(lista_reagenti, filter_name == "R")

letter_S <- subset(lista_reagenti, filter_name == "S")

letter_T <- subset(lista_reagenti, filter_name == "T")

letter_U <- subset(lista_reagenti, filter_name == "U")

letter_V <- subset(lista_reagenti, filter_name == "V")

letter_W <- subset(lista_reagenti, filter_name == "W")

letter_X <- subset(lista_reagenti, filter_name == "X")

letter_Y <- subset(lista_reagenti, filter_name == "Y")

letter_Z <- subset(lista_reagenti, filter_name == "Z")

```

**Laboratory Responsible**: Fabio Valentinuzzi - [email](mailto:fabio.valentinuzzi@unibz.it)

**Laboratory Technician**: Fabio Valentinuzzi - [email](mailto:fabio.valentinuzzi@unibz.it) [phone](tel:+390471017627) 

**General technician contact** - [email](mailto:techstaff.agriculture@unibz.it) [phone](tel:+393316742962)

**Call [112](tel:112) for Emergency**

Last update: 10 / 01 / 2023

------------------------------------------------------------------------

### Last changes:

-   ..

------------------------------------------------------------------------

## A

```{r echo=FALSE}

letter_A <- letter_A %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_A[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## B

```{r echo=FALSE}

letter_B <- letter_B %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_B[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## C

```{r echo=FALSE}

letter_C <- letter_C %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_C[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## D

```{r echo=FALSE}

letter_D <- letter_D %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_D[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## E

```{r echo=FALSE}

letter_E <- letter_E %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_E[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## F

```{r echo=FALSE}

letter_F <- letter_F %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_F[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## G

```{r echo=FALSE}

letter_G <- letter_G %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_G[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## H

```{r echo=FALSE}

letter_H <- letter_H %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_H[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## I

```{r echo=FALSE}

letter_I <- letter_I %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_I[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## J

```{r echo=FALSE}

letter_J <- letter_J %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_J[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## K

```{r echo=FALSE}

letter_K <- letter_K %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_K[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## L

```{r echo=FALSE}

letter_L <- letter_L %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_L[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```

## M

```{r echo=FALSE}

letter_M <- letter_M %>%
  mutate(SDS = cell_spec("SDS", "html", link = sds))

letter_M[,-c(1,2,5,6,7,9,12)] %>%
  # mutate(
  #   Reagent = ifelse(Quantity == 0 | Note == "ending",
  #                 cell_spec(Reagent, "html", color = "red", bold = T),
  #                 cell_spec(Reagent, "html")),
  #   Quantity = ifelse(Quantity > 0,
  #                 cell_spec(Quantity, "html"),
  #                 cell_spec(Quantity, "html", color = "red", bold = T)),
  #   # Note = ifelse(Note == "not found" | Note =="ending",
  #   #               cell_spec(Note, "html", color = "red", bold = T),
  #   #               cell_spec(Note, "html"))
  # ) %>%
  kable(row.names = FALSE, align = "l","html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive", "condensed"), font_size = 14)

```